version: 2
jobs:
  build:
    working_directory: /go/src/github.com/VividCortex/ewma
    docker: 
      - image: circleci/golang:1.12.5
    environment:
      GO111MODULE: "off"

    steps:
      - checkout
      # get the latest dep
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure -v -vendor-only
      - run: go vet ./...
      - run: go test -race ./...
